site_name: Example of zig project documentation using mkdocstrings

plugins:
- mkdocstrings:
    default_handler: zig
    handlers:
      zig:
        options:
          # include:
          #   - "**/*.zig"
          # paths:
          #   - src
